import { NextResponse } from 'next/server'

// Redirect old /api/sitemap to the new /sitemap.xml generated by src/app/sitemap.ts
export async function GET() {
  const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://goalzone-live.vercel.app'
  return NextResponse.redirect(`${SITE_URL}/sitemap.xml`, 301)
}
