#!/usr/bin/env node
// ============================================================
// GOALZONE - Prisma Schema Auto-Switch (Cross-Platform)
// Automatically selects the correct Prisma schema based on
// DATABASE_URL protocol:
//   - file: → SQLite (local development)
//   - postgresql:// or postgres:// → PostgreSQL (Vercel/production)
//
// schema.prisma is in .gitignore and auto-generated by this script.
// The source of truth is schema.pg.prisma (PostgreSQL) and
// schema.sqlite.prisma (SQLite).
// ============================================================

const fs = require('fs');
const path = require('path');

// ---- Load .env file manually (no dependency needed) ----
function loadEnvFile() {
    const projectRoot = path.join(__dirname, '..');
    // Try .env, .env.local, .env.development
    const envFiles = ['.env', '.env.local', '.env.development'];
    let loaded = false;

    for (const file of envFiles) {
        const envPath = path.join(projectRoot, file);
        if (fs.existsSync(envPath)) {
            const content = fs.readFileSync(envPath, 'utf-8');
            const lines = content.split('\n');
            for (const line of lines) {
                const trimmed = line.trim();
                // Skip comments and empty lines
                if (!trimmed || trimmed.startsWith('#')) continue;
                // Parse KEY=VALUE
                const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
                if (match) {
                    const key = match[1];
                    let value = match[2];
                    // Remove surrounding quotes
                    if ((value.startsWith('"') && value.endsWith('"')) ||
                        (value.startsWith("'") && value.endsWith("'"))) {
                        value = value.slice(1, -1);
                    }
                    // Only set if not already in environment (env vars take priority)
                    if (!process.env[key]) {
                        process.env[key] = value;
                    }
                }
            }
            loaded = true;
        }
    }
    return loaded;
}

loadEnvFile();

// ---- Main logic ----
const SCHEMA_DIR = path.join(__dirname, '..', 'prisma');
const SQLITE_SCHEMA = path.join(SCHEMA_DIR, 'schema.sqlite.prisma');
const PG_SCHEMA = path.join(SCHEMA_DIR, 'schema.pg.prisma');
const ACTIVE_SCHEMA = path.join(SCHEMA_DIR, 'schema.prisma');

// Read DATABASE_URL (now loaded from .env)
let dbUrl = process.env.DATABASE_URL || '';

if (!dbUrl) {
    console.log('[prisma-switch] ⚠️  DATABASE_URL is not set. Defaulting to SQLite.');
    dbUrl = 'file:./db/custom.db';
} else {
    // Mask the URL for security (show protocol + host only)
    const masked = dbUrl.length > 30 ? dbUrl.substring(0, 15) + '***' + dbUrl.substring(dbUrl.length - 10) : dbUrl;
    console.log(`[prisma-switch] 📋 DATABASE_URL found: ${masked}`);
}

function copyFile(src, dest) {
    fs.copyFileSync(src, dest);
}

function getProvider(filePath) {
    const content = fs.readFileSync(filePath, 'utf-8');
    const match = content.match(/provider\s*=\s*"(\w+)"/);
    return match ? match[1] : 'unknown';
}

// Detect database type from URL protocol
if (dbUrl.startsWith('file:')) {
    console.log('[prisma-switch] 📦 Detected SQLite (file: protocol)');
    if (fs.existsSync(SQLITE_SCHEMA)) {
        copyFile(SQLITE_SCHEMA, ACTIVE_SCHEMA);
        console.log('[prisma-switch] ✅ Copied schema.sqlite.prisma → schema.prisma');
    } else {
        console.log('[prisma-switch] ⚠️  schema.sqlite.prisma not found. Keeping current schema.');
    }
} else if (dbUrl.startsWith('postgres:') || dbUrl.startsWith('postgresql:')) {
    console.log('[prisma-switch] 🐘 Detected PostgreSQL (postgresql: protocol)');
    if (fs.existsSync(PG_SCHEMA)) {
        copyFile(PG_SCHEMA, ACTIVE_SCHEMA);
        console.log('[prisma-switch] ✅ Copied schema.pg.prisma → schema.prisma');
    } else {
        console.log('[prisma-switch] ⚠️  schema.pg.prisma not found. Keeping current schema.');
    }
} else {
    console.log(`[prisma-switch] ❓ Unknown DATABASE_URL protocol: ${dbUrl.substring(0, 20)}...`);
    console.log('[prisma-switch]    Expected "file:" for SQLite or "postgresql:" for PostgreSQL');
    console.log('[prisma-switch]    Defaulting to PostgreSQL schema (Vercel default).');
    if (fs.existsSync(PG_SCHEMA)) {
        copyFile(PG_SCHEMA, ACTIVE_SCHEMA);
    } else if (fs.existsSync(SQLITE_SCHEMA)) {
        copyFile(SQLITE_SCHEMA, ACTIVE_SCHEMA);
    }
}

// Safety check: if schema.prisma still doesn't exist, create from PG schema
if (!fs.existsSync(ACTIVE_SCHEMA)) {
    console.log('[prisma-switch] ⚠️  schema.prisma does not exist. Creating from schema.pg.prisma...');
    if (fs.existsSync(PG_SCHEMA)) {
        copyFile(PG_SCHEMA, ACTIVE_SCHEMA);
        console.log('[prisma-switch] ✅ Created schema.prisma from schema.pg.prisma');
    } else {
        console.log('[prisma-switch] ❌ Neither schema.prisma nor schema.pg.prisma exists!');
        process.exit(1);
    }
}

const provider = getProvider(ACTIVE_SCHEMA);
console.log(`[prisma-switch] ✅ Active schema provider: ${provider}`);
